#!/usr/bin/python

import argparse
import os
import platform
import getpass
import sys
import email
import smtplib
import logging

import lightbts

# Initialize

parser = argparse.ArgumentParser(description='Process incoming bug reports.', epilog='Report bugs to guus@sliepen.org.')
parser.add_argument('-a', '--admin', metavar='ADDRESS', help='admin email address')
parser.add_argument('-d', '--data', metavar='DIR', help='directory where LightBTS stores its data')
parser.add_argument('-f', '--from', metavar='ADDRESS', help='email address of this instance of LightBTS', dest='myaddress')
parser.add_argument('-n', '--name', metavar='NAME', help='name for this instance of LightBTS', default='LightBTS')
parser.add_argument('--version', action='version', version='LightBTS ' + lightbts.__version__)

args = parser.parse_args()

if args.myaddress:
    myaddress = args.myaddress
else:
    myaddress = getpass.getuser() + '@' + platform.node()

admin = args.admin

if args.data:
    lightbts.init(args.data)
else:
    lightbts.init(os.environ['HOME'])

msg = email.message_from_file(sys.stdin)

if msg['Auto-Submitted'] == 'auto-replied' or msg['X-Autoreply'] or msg['X-Autorespond']:
    logger.warning('Ignoring auto-replied message from ' + msg['From'])
    exit(0)

(bug, new) = lightbts.import_email(msg)

if bug is None:
    # This is a duplicate message, ignore.
    exit(0)

if new:
    subject = 'Bug#' + str(bug.id) + ': ' + msg['Subject']
    tmpl = lightbts.get_template("new.txt", "Thank you for reporting a bug, which has been assigned number ${id}.")
else:
    subject = msg['Subject']
    tmpl = lightbts.get_template("reply.txt", "Thank you for reporting additional information for bug number ${id}.")

text = tmpl.substitute({'id': bug._id})
reply = email.MIMEText.MIMEText(text)

reply['From'] = args.name + ' <' + myaddress + '>'
reply['To'] = msg['From']
reply['Subject'] = subject
reply['User-Agent'] = 'LightBTS/' + lightbts.__version__
reply['Auto-Submitted'] = 'auto-replied'
reply['X-Auto-Response-Suppress'] = 'All'

reply['Message-Id'] = email.utils.make_msgid('LightBTS')
reply['In-Reply-To'] = msg['Message-ID']

smtp = smtplib.SMTP(lightbts.smtphost)
smtp.sendmail(reply['From'], reply['To'], reply.as_string())

lightbts.record_msgid(bug.id, email.utils.unquote(reply['Message-Id']))

# Send a copy to the admin

if admin:
    msg.replace_header('Subject', subject)
    msg['Reply-To'] = myaddress
    smtp.sendmail(msg['From'], admin, msg.as_string())

lightbts.exit()
