.Dd 2018-04-17
.Dt LBTS-HELP 1
.\" Manual page created by:
.\" Guus Sliepen <guus@lightbts.info>
.Sh NAME
.Nm lbts help
.Nd show a help message
.Sh SYNOPSIS
.Nm lbts help
.Op Ar command
.Pp
.Nm lbts
.Op Ar command
.Fl h | -help
.Sh DESCRIPTION
If a
.Ar command
is specified, show the manual page for the given command.
Otherwise, print the synopsis and a list of the supported commands.
.Sh SEE ALSO
.Xr lbts 1 ,
.Xr man 1 .
.Sh AUTHOR
.An "Guus Sliepen" Aq guus@lightbts.info
