.Dd 2018-04-17
.Dt LBTS-REPLY 1
.\" Manual page created by:
.\" Guus Sliepen <guus@lightbts.info>
.Sh NAME
.Nm lbts reply
.Nd reply to an existing ticket
.Sh SYNOPSIS
.Nm lbts reply
.Op Fl V Ar version
.Op Fl T Ar tag
.Op Fl S Ar severity
.Op Fl m Ar message
.Ar id
.Sh DESCRIPTION
The command replies to an existing ticket.
The
.Ar id
can either be a ticket or a message ID.
If the command is run interactively, then an editor will be invoked where the reply message can be filled in.
Otherwise, a message is expected to be given using the
.Fl m
option or to be provided via stdin.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl V Ar version
Record the version where the issue was found.
This option can be specified multiple times.
.It Fl T Ar tag
Add the given tag for this issue.
This option can be specified multiple times.
.It Fl S Ar severity
Specify a new severity for the issue.
.It Fl m Ar message
Use the given message instead of invoking an editor or reading one from stdin.
.El
.Sh SEE ALSO
.Xr lbts 1 .
.Sh AUTHOR
.An "Guus Sliepen" Aq guus@lightbts.info
